const SCREENS = {
   PHONE_SIGN_IN: 'PhoneSignInScreen',
   WELCOME_SCREEN: 'WelcomeScreen',
   SELECT_LANGUAGE_SCREEN: 'SelectLanguageScreen',
   SIGN_UP_SCREEN: 'SignUpScreen',
   SIGN_IN_SCREEN: 'SignInScreen',
   OTP_VERIFICATION: 'OTPVerificationScreen',
   FIND_ROUTE: 'FindRouteScreen',
   MY_ROUTES: 'MyRoutesScreen',
   FOLLOW_PROGRESS: 'FollowProgressScreen',
   NOTIFICATIONS: 'NotificationsScreen',
   PROFILE: 'ProfileScreen',
   ADMIN_CARS: 'AdminCarsScreen',
   ADMIN_ORDERS: 'AdminOrdersScreen',
   ADMIN_CARS_FORM: 'AdminCarsFormScreen',
   ADMIN_DRIVERS: 'AdminDriversScreen',
   ADMIN_DRIVERS_FORM: 'AdminDriversFormScreen',
   ADMIN_SCHEDULES: 'AdminSchedulesScreen',
   ADMIN_SCHEDULES_FORM: 'AdminSchedulesFormScreen',
   ADMIN_FORMS: 'AdminFormsScreen',
   DRIVER_SCHEDULES: 'DriverSchedulesScreen',
   FORGOT_PASSWORD: 'ForgotPasswordScreen',
} as const;

export default SCREENS;
